version: '3'

services:
  web:
    image: nginx:stable-alpine
    container_name: web_supers
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME_1}, www.${DOMAIN_NAME_1}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN_NAME_1}, www.${DOMAIN_NAME_1}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
      - DEBUG=1
    volumes:
      - ${CONTAINER_DIR}/public:/usr/share/nginx/html:ro
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK}

volumes:
  conf:
  certs: